// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARE6LXmLLsxcWeMQ5zaf6841dxaAQSv1o',
    appId: '1:958179923371:web:31d4d608c8f44e50c5eeee',
    messagingSenderId: '958179923371',
    projectId: 'sb-129-eab59',
    authDomain: 'sb-129-eab59.firebaseapp.com',
    storageBucket: 'sb-129-eab59.appspot.com',
    measurementId: 'G-SW9S9VXXDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MqdJn2ebvnSTOHju6UfzUeLzyaQhDWk',
    appId: '1:958179923371:android:913f8ab0a6cc8136c5eeee',
    messagingSenderId: '958179923371',
    projectId: 'sb-129-eab59',
    storageBucket: 'sb-129-eab59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWJbr0ZZLtN32lx3sxz82u85bGWmS3Ec',
    appId: '1:958179923371:ios:fb8efd991c106761c5eeee',
    messagingSenderId: '958179923371',
    projectId: 'sb-129-eab59',
    storageBucket: 'sb-129-eab59.appspot.com',
    iosClientId: '958179923371-3l1cbl4vnf7ge03dlk6mf1thc16lf600.apps.googleusercontent.com',
    iosBundleId: 'com.example.sb129',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWJbr0ZZLtN32lx3sxz82u85bGWmS3Ec',
    appId: '1:958179923371:ios:fb8efd991c106761c5eeee',
    messagingSenderId: '958179923371',
    projectId: 'sb-129-eab59',
    storageBucket: 'sb-129-eab59.appspot.com',
    iosClientId: '958179923371-3l1cbl4vnf7ge03dlk6mf1thc16lf600.apps.googleusercontent.com',
    iosBundleId: 'com.example.sb129',
  );
}
